autofuzz: Do not print ClassNotFoundException
Due to our heuristic for nested classes, the exception message looks
like this:
```
java.lang.ClassNotFoundException: com$example$foo$Bar
```
Since it doesn't contain any new information, we do not emit it.