ci: Disable the disk cache
The disk cache was based on GitHub Action's immutable caches with a
static cache and thus likely contained outdated results. It also results
in spurious persistent failures on Windows such as:

```
ERROR: D:/a/jazzer/jazzer/deploy/BUILD.bazel:65:12: MergeJars deploy/jazzer-junit-project-src.jar failed: Exec failed due to IOException: 2 errors during bulk transfer:
java.io.IOException: D:/a/jazzer/jazzer/%HOME%/bazel-disk/cas/44/44e1a1356c8b7423f3b6c8cef5d75fdd6bf193f03d7bc416f81a3c3cd86166a2 (Permission denied)
java.io.IOException: D:/a/jazzer/jazzer/%HOME%/bazel-disk/cas/44/44e1a1356c8b7423f3b6c8cef5d75fdd6bf193f03d7bc416f81a3c3cd86166a2 (Permission denied)
```

Since we already use a remote cache, disabling the disk cache should not
harm build times. In fact, the CI Sense jobs didn't even use the cache,
but paid the cost for setting it up.